# Generated by Django 5.1.1 on 2025-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0002_planmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
