# Generated by Django 5.1.1 on 2025-02-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0003_planmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planmodel',
            old_name='quantity',
            new_name='locations',
        ),
        migrations.AddField(
            model_name='planmodel',
            name='tables',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
