# Generated by Django 5.1.1 on 2025-02-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0005_alter_planmodel_locations_alter_planmodel_tables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='plan_type',
            field=models.CharField(choices=[('free', 'FREE'), ('pay', 'PAY')], default='pay', max_length=10),
            preserve_default=False,
        ),
    ]
