# Generated by Django 5.1.1 on 2025-02-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0009_alter_planmodel_plan_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planmodel',
            table='plans',
        ),
    ]
