# Generated by Django 5.1.1 on 2025-02-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0011_subscriptionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownermodel',
            name='plan_id',
        ),
    ]
